### ISSUE TITLE
Cybersquatting?

### ISSUE THREAD

**Issue by gmacario** [gunnarx/gocd-setup#1]
Hi @gunnarx,

Just noticed https://github.com/gunnarx/gocd-setup/blob/master/go_server#L1 and [this](http://whois.domaintools.com/genivigo.com)

Uhmm... I wonder whether this is compliant with [that](http://www.genivi.org/sites/default/files/GENIVI_Trademark_and_Logo_Usage_2013-12.pdf) :smiley:

**Comment by gunnarx** [comment]
I don't know if it is, but obviously things like names are easily changed.
